Improve the method of detecting system locale
chocolatey-community/chocolatey-coreteampackages pull request #1698
Opened 2021-08-10 00:39 UTC by msoxzw

The current method of detecting system locale is not robust enough. Take "zh-HK" as an example, it should be fallback to "zh_TW", but this package fallback "zh-HK" to "en-US". This commit detects fallback locale by sending `Accept-Language: zh-HK` header to https://www.mozilla.org/ to get Mozilla fallback locale.

2021-09-11 19:45 UTC, majkinetor requested changes
![image](https://user-images.githubusercontent.com/85767/132959714-037f763d-d995-49de-bbe0-9b328d7b7d72.png)

Omitting MaximumRedirects doesn't give location either.

2021-09-11 19:47 UTC, majkinetor commented
Nvm, above is in `pwsh`, in powershell it works.

2021-09-11 19:47 UTC, merged

2021-10-04 11:16 UTC, thoscut commented
This change breaks internalization of the package with 
```batch
choco download firefox --internalize --internalize-all-urls
```

The installation of the package fails:
```batch
Firefox v92.0.1
firefox package files upgrade completed. Performing other installation steps.
ERROR: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Illegal characters in path.
The upgrade of firefox was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\Firefox\tools\chocolateyInstall.ps1'.
```

2021-10-06 01:04 UTC, TheCakeIsNaOH commented
@thoscut You may want to contact support to see if they would have any workarounds for this issue. I'm not sure if it would work, but you could try internalizing without `--internalize-all-urls`

Two other options would be to internalize this package manually, or possibly use [choco-remixer](https://github.com/TheCakeIsNaOH/choco-remixer) [Note it is completely unofficial]

2021-10-06 15:36 UTC, pauby commented
@thoscut That internalization works for me:

```
> choco download firefox --internalize --internalize-all-urls
Chocolatey v0.11.1 Business
Downloading existing package(s) to C:\Users\Paul\download

chocolatey-core.extension v1.3.5.1

Recompile not necessary. There is no install script. Use the nupkg file
 as is in 'C:\Users\Paul\download\chocolatey-core.extension'

Firefox v93.0
Found internalizable Chocolatey functions. Inspecting values for remote resources.

Adding -UseOriginalLocation to Install-ChocolateyPackage (if found).
 There is a bug in Chocolatey v0.10.1 that occurs when there is only
 one url replaced (no 32 and 64 bit Windows). Be sure to remove the
 parameter and recompile if you have any 0.10.1 installations. You
 can also turn off the feature 'internalizeAppendUseOriginalLocation' to not append
Updating chocolateyInstall.ps1 with local resources.
Recompiling package.

Recompiled package files available at 'C:\Users\Paul\download\Firefox'
Recompiled nupkg available in 'C:\Users\Paul'
```

However, [these lines](https://github.com/chocolatey-community/chocolatey-coreteampackages/pull/1698/files#diff-b83df586bc956a7b171344bc3c71ac191fe3fe6893aec94a0957c3287fa4ab0bR46-R48) look to be problematic if there is no valid response back (what would `$fallBackLocale` actually be).

2021-10-06 16:26 UTC, pauby commented
I've raised a [PR](https://github.com/chocolatey-community/chocolatey-coreteampackages/pull/1724) to try and address this.